### ISSUE TITLE
nodes problem

### ISSUE THREAD

**Issue by NotYourTypicalPerson** [Elliotproject/ELLI#1]
Hey , what are the peers ip?
nodes ip?

**Comment by Elliotproject** [comment]
Hello! Thank you for contacting us, net is now working in test mode, that's why we haven't published ip adresses yet. All information about peers and nodes will be added at the same time with official launch on this week. You can join our telegram(https://t.me/ellicoin) and discord channel (https://discord.gg/cE4Nefv) for upcoming announcementsю Also, we are going to launch a website and make an announcement on bitcointalk in next few days.

**Comment by elliotproject** [comment]
Have you compiled dependencies for this host?
